language: node_js
node_js:
- '4.1'
install:
# - "./node_modules/protractor/bin/webdriver-manager update --standalone --chrome"
before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
# - "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
# - sleep 3
script:
- gulp karma
- gulp test